<?php

namespace App\Services;

class AreasData
{
    /**
     * Get the full list of 27 serviced Dubai communities.
     */
    public static function getCommunities(): array
    {
        return [
            [
                'id' => 'nad-al-sheba',
                'name' => 'Nad Al Sheba 1-4',
                'lat' => 25.1432,
                'lng' => 55.3340,
                'zone' => 'Central & MBR City',
                'badge' => 'Same-Day Dispatch',
                'tagline' => 'Luxury Villas & Meydan Residences',
                'featured' => true,
            ],
            [
                'id' => 'international-city',
                'name' => 'International City',
                'lat' => 25.1633,
                'lng' => 55.4050,
                'zone' => 'East Dubai',
                'badge' => 'Daily Teams Available',
                'tagline' => 'Apartment Clusters & Retail Strips',
                'featured' => false,
            ],
            [
                'id' => 'dubai-silicon-oasis',
                'name' => 'Dubai Silicon Oasis',
                'lat' => 25.1228,
                'lng' => 55.3814,
                'zone' => 'Dubailand & Tech Hub',
                'badge' => 'High Demand Area',
                'tagline' => 'Cedre & Semmer Villas, Tech Towers',
                'featured' => true,
            ],
            [
                'id' => 'liwan',
                'name' => 'Liwan',
                'lat' => 25.1115,
                'lng' => 55.3685,
                'zone' => 'Dubailand & Tech Hub',
                'badge' => 'Full Coverage',
                'tagline' => 'Quebec, San Francisco & Mazaya Residences',
                'featured' => false,
            ],
            [
                'id' => 'dubailand',
                'name' => 'Dubailand',
                'lat' => 25.0780,
                'lng' => 55.3320,
                'zone' => 'Dubailand & Suburbs',
                'badge' => 'Fast Dispatch',
                'tagline' => 'Expansive Residential Neighborhoods',
                'featured' => false,
            ],
            [
                'id' => 'falcon-city-of-wonders',
                'name' => 'Falcon City of Wonders',
                'lat' => 25.0935,
                'lng' => 55.3435,
                'zone' => 'Dubailand & Suburbs',
                'badge' => 'Villa Specialists',
                'tagline' => 'Signature Luxury Villas & Townhouses',
                'featured' => false,
            ],
            [
                'id' => 'warsan-4',
                'name' => 'Warsan 4',
                'lat' => 25.1580,
                'lng' => 55.4210,
                'zone' => 'East Dubai',
                'badge' => 'Daily Cleaning',
                'tagline' => 'Modern Apartment Communities',
                'featured' => false,
            ],
            [
                'id' => 'the-villa',
                'name' => 'The Villa',
                'lat' => 25.0833,
                'lng' => 55.3722,
                'zone' => 'Dubailand & Suburbs',
                'badge' => 'Deep Cleaning Hub',
                'tagline' => 'Centro, Cordoba, Ponderosa & Aldea',
                'featured' => true,
            ],
            [
                'id' => 'villanova',
                'name' => 'Villanova',
                'lat' => 25.0682,
                'lng' => 55.3621,
                'zone' => 'Dubailand & Suburbs',
                'badge' => 'Same-Day Dispatch',
                'tagline' => 'Amaranta & La Quinta Mediterranean Villas',
                'featured' => true,
            ],
            [
                'id' => 'tilal-al-ghaf',
                'name' => 'Tilal Al Ghaf',
                'lat' => 25.0210,
                'lng' => 55.2280,
                'zone' => 'New Dubai & South',
                'badge' => 'Premium Service',
                'tagline' => 'Elan, Harmony & Aura Luxury Townhouses',
                'featured' => true,
            ],
            [
                'id' => 'dubai-sports-city',
                'name' => 'Dubai Sports City',
                'lat' => 25.0445,
                'lng' => 55.2215,
                'zone' => 'New Dubai & South',
                'badge' => 'Daily Available',
                'tagline' => 'Canal Residence, Elite Sports Towers',
                'featured' => false,
            ],
            [
                'id' => 'dubai-motor-city',
                'name' => 'Dubai Motor City',
                'lat' => 25.0505,
                'lng' => 55.2395,
                'zone' => 'New Dubai & South',
                'badge' => 'Fast Dispatch',
                'tagline' => 'Uptown Motor City & Green Community',
                'featured' => true,
            ],
            [
                'id' => 'dubai-studio-city',
                'name' => 'Dubai Studio City',
                'lat' => 25.0380,
                'lng' => 55.2490,
                'zone' => 'New Dubai & South',
                'badge' => 'Office & Residential',
                'tagline' => 'Studio Buildings & Commercial Suites',
                'featured' => false,
            ],
            [
                'id' => 'arabian-ranches',
                'name' => 'Arabian Ranches 1-3',
                'lat' => 25.0558,
                'lng' => 55.2685,
                'zone' => 'New Dubai & South',
                'badge' => 'Top Serviced Area',
                'tagline' => 'Saheel, Palmera, Al Reem, Sun & Joy',
                'featured' => true,
            ],
            [
                'id' => 'dubai-production-city',
                'name' => 'Dubai Production City',
                'lat' => 25.0315,
                'lng' => 55.1870,
                'zone' => 'New Dubai & South',
                'badge' => 'Apartment Teams',
                'tagline' => 'IMPZ, Midtown & Lakeside Towers',
                'featured' => false,
            ],
            [
                'id' => 'damac-hills',
                'name' => 'DAMAC Hills',
                'lat' => 25.0280,
                'lng' => 55.2530,
                'zone' => 'New Dubai & South',
                'badge' => 'Golf Estates Hub',
                'tagline' => 'Trump Estates, Rockwood, Pelham Villas',
                'featured' => true,
            ],
            [
                'id' => 'mudon',
                'name' => 'Mudon',
                'lat' => 25.0375,
                'lng' => 55.2890,
                'zone' => 'Dubailand & South',
                'badge' => 'Family Communities',
                'tagline' => 'Arabella, Rahat & Naseem Townhouses',
                'featured' => true,
            ],
            [
                'id' => 'serena',
                'name' => 'Serena',
                'lat' => 25.0440,
                'lng' => 55.3050,
                'zone' => 'Dubailand & South',
                'badge' => 'Same-Day Dispatch',
                'tagline' => 'Bella Casa, Casa Dora & Casa Viva',
                'featured' => false,
            ],
            [
                'id' => 'rukan',
                'name' => 'Rukan',
                'lat' => 25.0510,
                'lng' => 55.3210,
                'zone' => 'Dubailand & South',
                'badge' => 'Modern Lofts',
                'tagline' => 'Rukan Lofts & Dubailand Green Enclave',
                'featured' => false,
            ],
            [
                'id' => 'layan',
                'name' => 'Layan',
                'lat' => 25.0250,
                'lng' => 55.3120,
                'zone' => 'Dubailand & South',
                'badge' => 'Gated Villas',
                'tagline' => 'Private Mediterranean Villas & Gardens',
                'featured' => false,
            ],
            [
                'id' => 'the-sustainable-city',
                'name' => 'The Sustainable City',
                'lat' => 25.0270,
                'lng' => 55.2810,
                'zone' => 'New Dubai & South',
                'badge' => 'Eco-Cleaning Hub',
                'tagline' => 'Eco-friendly Villas with Green Sanitization',
                'featured' => false,
            ],
            [
                'id' => 'al-waha',
                'name' => 'Al Waha',
                'lat' => 25.0305,
                'lng' => 55.3080,
                'zone' => 'Dubailand & South',
                'badge' => 'Full Coverage',
                'tagline' => 'Tranquil Villa & Townhouse Community',
                'featured' => false,
            ],
            [
                'id' => 'arjan',
                'name' => 'Arjan',
                'lat' => 25.0620,
                'lng' => 55.2370,
                'zone' => 'New Dubai & South',
                'badge' => 'Fast Dispatch',
                'tagline' => 'Miracle Garden Enclave, Lincoln Park',
                'featured' => false,
            ],
            [
                'id' => 'al-barari',
                'name' => 'Al Barari',
                'lat' => 25.1010,
                'lng' => 55.3150,
                'zone' => 'Central & MBR City',
                'badge' => 'Ultra-Luxury Service',
                'tagline' => 'Seventh Heaven, Ashjar & Botanical Villas',
                'featured' => true,
            ],
            [
                'id' => 'al-warqa',
                'name' => 'Al Warqa',
                'lat' => 25.1850,
                'lng' => 55.3950,
                'zone' => 'East Dubai',
                'badge' => 'Family Homes',
                'tagline' => 'Al Warqaa 1 to 4 & Safari Park District',
                'featured' => false,
            ],
            [
                'id' => 'mirdif',
                'name' => 'Mirdif',
                'lat' => 25.2210,
                'lng' => 55.4190,
                'zone' => 'East Dubai',
                'badge' => 'Top Residential Hub',
                'tagline' => 'Uptown Mirdif, Shorooq & Ghoroob',
                'featured' => true,
            ],
            [
                'id' => 'sobha-hartland',
                'name' => 'Sobha Hartland',
                'lat' => 25.1765,
                'lng' => 55.3120,
                'zone' => 'Central & MBR City',
                'badge' => 'Waterfront & Greens',
                'tagline' => 'MBR City Greens, Crest & Forest Villas',
                'featured' => true,
            ],
        ];
    }

    /**
     * Get specific completed jobs (homes and offices) where cleaning was performed,
     * with real cleaning work photos to reveal on hover or tap.
     */
    public static function getCompletedJobs(): array
    {
        return [
            [
                'id' => 'job-ummsuqeim',
                'title' => 'Umm Suqeim Street',
                'subtitle' => 'Al Barsha 2 next to Marina H...',
                'community' => 'Al Barsha / Umm Suqeim',
                'type' => 'Commercial & Villa Deep Clean',
                'lat' => 25.1120,
                'lng' => 55.2050,
                'rating' => 5.0,
                'photo' => asset('services images/commercial-cleaning.png'),
                'description' => 'Comprehensive deep sanitization, exterior glass detailing & floor polishing.',
            ],
            [
                'id' => 'job-palmjumeirah',
                'title' => 'Palm Jumeirah',
                'subtitle' => 'Center of Palm / Shoreline',
                'community' => 'Palm Jumeirah',
                'type' => 'Luxury Waterfront Residence',
                'lat' => 25.1124,
                'lng' => 55.1389,
                'rating' => 5.0,
                'photo' => asset('services images/villa-deep-cleaning.png'),
                'description' => 'Balcony glass wash, marble restoration & antibacterial kitchen sanitization.',
            ],
            [
                'id' => 'job-dubaifestival',
                'title' => 'Dubai Festival City',
                'subtitle' => 'Dubai Festival / Badia',
                'community' => 'Dubai Festival City',
                'type' => 'Residential & Corporate Clean',
                'lat' => 25.2230,
                'lng' => 55.3520,
                'rating' => 5.0,
                'photo' => asset('services images/deep-cleaning.png'),
                'description' => 'After-tenancy deep clean, AC vent detailing and full bathroom descaling.',
            ],
            [
                'id' => 'job-mirdif',
                'title' => 'City Centre Mirdif',
                'subtitle' => 'Mirdif / Uptown Enclave',
                'community' => 'Mirdif',
                'type' => 'Standalone Villa Deep Clean',
                'lat' => 25.2210,
                'lng' => 55.4190,
                'rating' => 5.0,
                'photo' => asset('services images/villa-deep-cleaning.png'),
                'description' => 'Whole-house deep scrub, carpet steam extraction & outdoor patio pressure wash.',
            ],
            [
                'id' => 'job-jumeirahpavilion',
                'title' => 'Jumeirah Pavilion',
                'subtitle' => 'Jumeirah Park / Islands',
                'community' => 'Jumeirah Park',
                'type' => 'Luxury Villa Deep Cleaning',
                'lat' => 25.0640,
                'lng' => 55.1680,
                'rating' => 5.0,
                'photo' => asset('services images/sofa-cleaning.png'),
                'description' => 'High-ceiling dusting, sofa upholstery steaming & tile grout cleaning.',
            ],
            [
                'id' => 'job-festivalplaza',
                'title' => 'Festival Plaza',
                'subtitle' => 'Jebel Ali Village',
                'community' => 'Jebel Ali Village',
                'type' => 'Modern Apartment Deep Clean',
                'lat' => 25.0250,
                'lng' => 55.1150,
                'rating' => 5.0,
                'photo' => asset('services images/apartment-deep-cleaning.png'),
                'description' => 'Move-in deep clean, appliances grease removal & hygienic sanitization.',
            ],
            [
                'id' => 'job-mudon',
                'title' => 'Mudon Community',
                'subtitle' => 'Arabella & Rahat, Mudon',
                'community' => 'Mudon',
                'type' => 'Townhouse Deep Clean',
                'lat' => 25.0375,
                'lng' => 55.2890,
                'rating' => 5.0,
                'photo' => asset('services images/window-cleaning.png'),
                'description' => 'Staircase detailing, window track steam cleaning & bedroom wash.',
            ],
            [
                'id' => 'job-productioncity',
                'title' => 'City Centre Me\'aisem',
                'subtitle' => 'Dubai Production City (IMPZ)',
                'community' => 'Dubai Production City',
                'type' => 'Apartment Suite Cleaning',
                'lat' => 25.0315,
                'lng' => 55.1870,
                'rating' => 5.0,
                'photo' => asset('services images/apartment-deep-cleaning.png'),
                'description' => 'Complete kitchen degreasing, bathroom steam wash & odor elimination.',
            ],
            [
                'id' => 'job-arabianranches',
                'title' => 'Arabian Ranches 2',
                'subtitle' => 'Palmera & Saheel Villas',
                'community' => 'Arabian Ranches',
                'type' => 'Standalone Villa Deep Clean',
                'lat' => 25.0558,
                'lng' => 55.2685,
                'rating' => 5.0,
                'photo' => asset('services images/villa-deep-cleaning.png'),
                'description' => 'Villa floor buffing, chandelier dusting & bathroom descaling.',
            ],
            [
                'id' => 'job-dso',
                'title' => 'Dubai Silicon Oasis',
                'subtitle' => 'Cedre & Semmer Villas',
                'community' => 'Dubai Silicon Oasis',
                'type' => 'Tech Office & Villa Sanitization',
                'lat' => 25.1228,
                'lng' => 55.3814,
                'rating' => 5.0,
                'photo' => asset('services images/commercial-cleaning.png'),
                'description' => 'Commercial office deep clean and villa move-in handover service.',
            ],
            [
                'id' => 'job-damachills',
                'title' => 'DAMAC Hills',
                'subtitle' => 'Rockwood & Akoya Golf Villas',
                'community' => 'DAMAC Hills',
                'type' => 'Golf Villa Deep Clean',
                'lat' => 25.0280,
                'lng' => 55.2530,
                'rating' => 5.0,
                'photo' => asset('services images/carpet-cleaning.png'),
                'description' => 'Floor-to-ceiling panoramic glass cleaning & luxury carpet shampooing.',
            ],
            [
                'id' => 'job-sobhahartland',
                'title' => 'Sobha Hartland',
                'subtitle' => 'MBR City Greens & Waterfront',
                'community' => 'Sobha Hartland',
                'type' => 'Luxury Waterfront Apartment',
                'lat' => 25.1765,
                'lng' => 55.3120,
                'rating' => 5.0,
                'photo' => asset('services images/deep-cleaning.png'),
                'description' => 'Complete handover deep clean and balcony floor restoration.',
            ],
        ];
    }

    /**
     * Get PureDropCleaning verified Google Business Profile.
     */
    public static function getOffices(): array
    {
        return [
            [
                'id' => 'office-main',
                'name' => 'Pure Drop Building Cleaning Services LLC',
                'role' => 'Official Verified Google Business Profile',
                'address' => 'Al Mankhool / Bur Dubai / Dubai, UAE',
                'lat' => 25.2373605,
                'lng' => 55.2812056,
                'phone' => '+971 56 217 0386',
                'email' => 'info.puredropcleaning@gmail.com',
                'hours' => 'Monday – Sunday: 7:00 AM – 9:00 PM',
                'gmaps_url' => 'https://maps.app.goo.gl/JXGtjbeuHYw3mzT69',
                'embed_url' => 'https://maps.google.com/maps?q=Pure+Drop+Building+Cleaning+Services+LLC+Dubai&t=&z=14&ie=UTF8&iwloc=&output=embed',
                'is_primary' => true,
            ],
        ];
    }
}
